GET http://localhost:3000/user/login?email=a&password=a

###

GET http://10.236.39.205:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwMDMyNjYwMywiZXhwIjoxNzAwMzMwMjAzfQ._NUcGxVJFHs4nF8uRjPc2oFWBH1b7tpju69sjBnZyx4